/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.Properties;
import javax.swing.JOptionPane;

/**
 *
 * @author Srdjan
 */
public class FPodesavanja extends javax.swing.JDialog {

    /**
     * Creates new form FPodesavanja
     *
     * @param parent
     * @param modal
     */
    public FPodesavanja(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        format();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtURL = new javax.swing.JTextField();
        jtxtUSERNAME = new javax.swing.JTextField();
        jbtnSacuvaj = new javax.swing.JButton();
        jbtnIzmeni = new javax.swing.JButton();
        jbtnDefault = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(200, 200, 200));

        jPanel1.setBackground(new java.awt.Color(200, 200, 200));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("URL");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Username");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Password");

        jbtnSacuvaj.setText("Sacuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        jbtnIzmeni.setText("Izmeni");
        jbtnIzmeni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnIzmeniActionPerformed(evt);
            }
        });

        jbtnDefault.setText("Default");
        jbtnDefault.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnDefaultActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbtnDefault)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 279, Short.MAX_VALUE)
                        .addComponent(jbtnIzmeni)
                        .addGap(35, 35, 35)
                        .addComponent(jbtnSacuvaj))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(74, 74, 74)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtURL, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                            .addComponent(jtxtUSERNAME)
                            .addComponent(jPasswordField1))))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtURL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtUSERNAME, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSacuvaj)
                    .addComponent(jbtnIzmeni)
                    .addComponent(jbtnDefault))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnDefaultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnDefaultActionPerformed
        jtxtURL.setText("jdbc:mysql://localhost/f1");
        jtxtUSERNAME.setText("root");
        jPasswordField1.setText("root");
    }//GEN-LAST:event_jbtnDefaultActionPerformed

    private void jbtnIzmeniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnIzmeniActionPerformed
        jPasswordField1.setEnabled(true);
        jtxtURL.setEnabled(true);
        jtxtUSERNAME.setEnabled(true);
        jbtnSacuvaj.setEnabled(true);
        JOptionPane.showMessageDialog(this, "Omogucena je izmena postavki!");
    }//GEN-LAST:event_jbtnIzmeniActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        Properties props = new Properties();
        try {
            File f = new File("New.properties");
            FileOutputStream out = new FileOutputStream("New.properties");
            props.setProperty("driver", "com.mysql.jdbc.Driver");
            props.setProperty("url", jtxtURL.getText());
            props.setProperty("user", jtxtUSERNAME.getText());
            props.setProperty("password", new String(jPasswordField1.getPassword()));
            props.store(out, null);
            out.close();
            JOptionPane.showMessageDialog(this, "Postavke uspesno sacuvane");
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Nije moguce pronaci properties fajl!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do greske pri upisu novih postavki!");
            jbtnDefault.doClick();
            jbtnSacuvaj.doClick();
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */
    private void format() {
        try {
            setLocationRelativeTo(null);
            FileInputStream in;
            try {
                in = new FileInputStream("New.properties");
            } catch (Exception e) {
                in = new FileInputStream("Settings.properties");
            }
            Properties props = new Properties();
            props.load(in);
            in.close();
            jtxtURL.setText(props.getProperty("url"));
            jtxtUSERNAME.setText(props.getProperty("user"));
            jPasswordField1.setText(props.getProperty("password"));
            jtxtURL.setEnabled(false);
            jPasswordField1.setEnabled(false);
            jtxtUSERNAME.setEnabled(false);
            jbtnSacuvaj.setEnabled(false);
            setVisible(true);
        } catch (FileNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "Nije moguce pronaci properties fajl!");
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Doslo je do neocekivane greska");
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JButton jbtnDefault;
    private javax.swing.JButton jbtnIzmeni;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JTextField jtxtURL;
    private javax.swing.JTextField jtxtUSERNAME;
    // End of variables declaration//GEN-END:variables
}
