/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.timovi;

import domen.Tim;
import domen.Vozilo;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import jdk.nashorn.internal.runtime.regexp.joni.exception.JOniException;
import komunikacija.Komunikacija;
import konstante.Operacija;
import kontroler.Kontroler;
import modeli.TabelaVozilaModel;
import transfer.Odgovor;
import transfer.Zahtev;

/**
 *
 * @author Srdjan
 */
public class FVozila extends javax.swing.JDialog {

    /**
     * Creates new form FVozili
     */
    public FVozila(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Kontroler.getInstance().setVozilaForma(this);
        format();
        vratiTimove();
        postaviModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboTim = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jTextMotor = new javax.swing.JTextField();
        jTextSasija = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Oznaka motora:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Oznaka šasije:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Odaberite tim:");

        jComboTim.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton1.setText("Odaberi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Obriši");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Dodaj");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Kraj");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextSasija, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextMotor, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jComboTim, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1))
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(256, 256, 256)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(239, 239, 239))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboTim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextMotor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextSasija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Kontroler.getInstance().setVozilaForma(null);
        getParent().setEnabled(true);
        getParent().requestFocus();
    }//GEN-LAST:event_formWindowClosed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            Tim t = (Tim) jComboTim.getSelectedItem();

            Vozilo v = new Vozilo();
            v.setTim(t);

            Zahtev z = new Zahtev(Operacija.VRATI_VOZILA, v);

            Komunikacija.getInstance().posaljiZahtev(z);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Nije moguce vratiti podatke o vozilima");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        String motor = jTextMotor.getText().trim();
        String sasija = jTextSasija.getText().trim();
        if (!motor.equals("") && !sasija.equals("")) {
            Tim t = (Tim) jComboTim.getSelectedItem();

            Vozilo v = new Vozilo();
            v.setOznakaMotora(motor);
            v.setOznakaSasije(sasija);
            v.setTim(t);
            TabelaVozilaModel m = (TabelaVozilaModel) jTable1.getModel();
            if(m.getLista().size()>=4){
                JOptionPane.showMessageDialog(this, "Tim u jednom trenutku moze imati najvise 4 vozila");
                return;
            }
            if(m.getLista().contains(v)){
                JOptionPane.showMessageDialog(this, "Vozilo sa unetim podacima vec postoji");
                return;
            }
            Zahtev z = new Zahtev(Operacija.SACUVAJ_VOZILO, v);

            Komunikacija.getInstance().posaljiZahtev(z);
            //m.getLista().add(v);
            //m.fireTableDataChanged();
        } else {
            JOptionPane.showMessageDialog(this, "Svi podaci moraju biti uneti!");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            TabelaVozilaModel m = (TabelaVozilaModel) jTable1.getModel();
            Vozilo v = m.getLista().get(jTable1.getSelectedRow());

            Zahtev z = new Zahtev(Operacija.IZBRISI_VOZILO, v);

            Komunikacija.getInstance().posaljiZahtev(z);
            m.getLista().remove(v);
            m.fireTableDataChanged();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Odaberite vozilo koje želite da obrišete");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboTim;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextMotor;
    private javax.swing.JTextField jTextSasija;
    // End of variables declaration//GEN-END:variables
    private void format() {
        setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());
        setLocationRelativeTo(null);
        setVisible(true);
    }

    public void popuniKomboTimovi(Odgovor o) {
        jComboTim.removeAllItems();
        ArrayList<Tim> timovi = (ArrayList<Tim>) o.getPodaci();

        for (Tim tim : timovi) {
            jComboTim.addItem(tim);
        }
    }

    private void vratiTimove() {
        Zahtev z = new Zahtev();
        z.setOperacija(Operacija.VRATI_TIMOVE);

        Komunikacija.getInstance().posaljiZahtev(z);
    }

    private void postaviModel() {
        TabelaVozilaModel model = new TabelaVozilaModel();
        jTable1.setModel(model);
    }

    public void ubaciVozilaUTabelu(Odgovor o) {
        TabelaVozilaModel m = (TabelaVozilaModel) jTable1.getModel();
        m.setLista((ArrayList<Vozilo>) o.getPodaci());
        m.fireTableDataChanged();
    }

    public void osveziModel(ArrayList<Vozilo> vozila) {
        TabelaVozilaModel m = (TabelaVozilaModel) jTable1.getModel();
        m.setLista(vozila);
        m.fireTableDataChanged();

    }

    public void obrisano(Odgovor o) {
        JOptionPane.showMessageDialog(this, o.getPoruka());
        
    }

    public void sacuvano(Odgovor o) {
        JOptionPane.showMessageDialog(this, o.getPoruka());
        TabelaVozilaModel m = (TabelaVozilaModel) jTable1.getModel();
        m.getLista().add((Vozilo) o.getPodaci());
        m.fireTableDataChanged();
    }

}
