/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme.trke;

import domen.Rezultat;
import domen.Trka;
import domen.Vozac;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import komunikacija.Komunikacija;
import konstante.Operacija;
import konstante.Poeni;
import kontroler.Kontroler;
import modeli.TabelaDodajRezultateModel;
import modeli.TabelaTrkaIzmenaModel;
import transfer.Odgovor;
import transfer.Zahtev;

/**
 *
 * @author Srdjan
 */
public class FDodajRezultate extends javax.swing.JDialog {

    /**
     * Creates new form FDodajRezultate
     */
    public FDodajRezultate(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Kontroler.getInstance().setDodajRezultateForma(this);
        format();
        vratiTrke();
        vratiVozace();
        postaviModelRezultata();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(720, 480));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("Trka:");

        jLabel2.setText("Vozač:");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setText("Startna pozicija:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jLabel4.setText("Konačna pozicija:");

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20" }));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Dodaj");
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Sačuvaj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Obriši");
        jButton3.setEnabled(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Kraj");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jButton5.setText("Odaberi");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 640, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(79, 79, 79)
                        .addComponent(jButton1)
                        .addGap(45, 45, 45)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton2))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        Kontroler.getInstance().setDodajRezultateForma(null);
        getParent().setEnabled(true);
        getParent().requestFocus();
    }//GEN-LAST:event_formWindowClosed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            int i = jTable2.getRowSorter().convertRowIndexToModel(jTable2.getSelectedRow());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Odaberite trku za unos rezultata");
            return;
        }
        TabelaTrkaIzmenaModel m = (TabelaTrkaIzmenaModel) jTable2.getModel();
        Trka t = m.getTrke().get(jTable2.getRowSorter().convertRowIndexToModel(jTable2.getSelectedRow()));
        Rezultat r = new Rezultat();
        r.setTrka(t);
        Zahtev z = new Zahtev(Operacija.VRATI_REZULTATE_TRKE, r);
        Komunikacija.getInstance().posaljiZahtev(z);
        jTable2.setEnabled(false);
        jTextField1.setEnabled(false);
        jButton1.setEnabled(true);
        jButton3.setEnabled(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = jTable2.getRowSorter().convertRowIndexToModel(jTable2.getSelectedRow());
        TabelaTrkaIzmenaModel m = (TabelaTrkaIzmenaModel) jTable2.getModel();
        Vozac v = (Vozac) jComboBox2.getSelectedItem();
        int stPoz = Integer.valueOf((String) jComboBox3.getSelectedItem());
        int krPoz = Integer.valueOf((String) jComboBox4.getSelectedItem());
        Rezultat r = new Rezultat();

        r.setKonacnaPozicija(krPoz);
        r.setStartnaPozicija(stPoz);
        r.setVozac(v);
        r.setTrka(m.getTrke().get(i));

        switch (krPoz) {
            case 1:
                r.setBrojPoena(Poeni.PRVI);
                break;
            case 2:
                r.setBrojPoena(Poeni.DRUGI);
                break;
            case 3:
                r.setBrojPoena(Poeni.TRECI);
                break;
            case 4:
                r.setBrojPoena(Poeni.CETVRTI);
                break;
            case 5:
                r.setBrojPoena(Poeni.PETI);
                break;
            case 6:
                r.setBrojPoena(Poeni.SESTI);
                break;
            case 7:
                r.setBrojPoena(Poeni.SEDMI);
                break;
            case 8:
                r.setBrojPoena(Poeni.OSMI);
                break;
            case 9:
                r.setBrojPoena(Poeni.DEVETI);
                break;
            case 10:
                r.setBrojPoena(Poeni.DESETI);
                break;
            default:
                r.setBrojPoena(0);
                break;
        }

        jComboBox2.removeItem(jComboBox2.getSelectedItem());
        jComboBox3.removeItem(jComboBox3.getSelectedItem());
        jComboBox4.removeItem(jComboBox4.getSelectedItem());
        TabelaDodajRezultateModel rezMod = (TabelaDodajRezultateModel) jTable1.getModel();
        rezMod.getLista().add(r);

        Collections.sort(rezMod.getLista(), rezCom);
        rezMod.fireTableDataChanged();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int i;
        try {
            i = jTable1.getSelectedRow();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Odaberite rezultat za brisanje");
            return;
        }
        TabelaDodajRezultateModel rezMod = (TabelaDodajRezultateModel) jTable1.getModel();
        Rezultat r = rezMod.getLista().get(i);
        rezMod.getLista().remove(i);
        jComboBox2.addItem(r.getVozac());
        jComboBox3.addItem(String.valueOf(r.getStartnaPozicija()));
        jComboBox4.addItem(String.valueOf(r.getKonacnaPozicija()));
        rezMod.fireTableDataChanged();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        TabelaDodajRezultateModel m = (TabelaDodajRezultateModel) jTable1.getModel();
        TabelaTrkaIzmenaModel m1 = (TabelaTrkaIzmenaModel) jTable2.getModel();
        if (m.getLista().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Unesite bar jedan rezultat");
            return;
        }
        Zahtev z = new Zahtev();
        for (Rezultat rezultat : m.getLista()) {
            if(rezultat.getBrojPoena()==Poeni.PRVI){
                Zahtev u = new Zahtev();
                int brP = rezultat.getVozac().getBrojPobeda()+1;
                Vozac v = rezultat.getVozac();
                v.setBrojPobeda(brP);
                u.setOperacija(Operacija.IZMENI_VOZACA);
                u.setPodaci(v);
                System.out.println(v.getBrojPobeda());
                Komunikacija.getInstance().posaljiZahtev(u);
            }
        }
        z.setOperacija(Operacija.SACUVAJ_REZULTATE_TRKE);
        z.setPodaci(m.getLista());
        Komunikacija.getInstance().posaljiZahtev(z);

        for (Rezultat r : m.getLista()) {
            jComboBox2.addItem(r.getVozac());
            jComboBox3.addItem(String.valueOf(r.getStartnaPozicija()));
            jComboBox4.addItem(String.valueOf(r.getKonacnaPozicija()));
        }
        m.setLista(new ArrayList<>());
        m.fireTableDataChanged();
        m1.getTrke().remove(jTable2.getRowSorter().convertRowIndexToModel(jTable2.getSelectedRow()));
        m1.fireTableDataChanged();
        restart();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

    private void format() {
        setIconImage(new ImageIcon(getClass().getResource("Icon.png")).getImage());
        setLocationRelativeTo(null);
        setVisible(true);
    }

    private void vratiVozace() {
        Zahtev z = new Zahtev();
        z.setOperacija(Operacija.VRATI_VOZACE);

        Komunikacija.getInstance().posaljiZahtev(z);
    }

    public void popuniKomboVozace(Odgovor o) {
        jComboBox2.removeAllItems();
        ArrayList<Vozac> vozaci = (ArrayList<Vozac>) o.getPodaci();

        for (Vozac v : vozaci) {
            jComboBox2.addItem(v);
        }

    }

    public void postaviModel(Odgovor o) {
        @SuppressWarnings("unchecked")
        TabelaTrkaIzmenaModel model = new TabelaTrkaIzmenaModel((ArrayList<Trka>) o.getPodaci());
        ArrayList<Trka> trkeIzm = new ArrayList<>();
        for (Trka trka : model.getTrke()) {
            if (trka.getDatumOdrzavanja().isBefore(LocalDateTime.now())) {
                trkeIzm.add(trka);
            }
        }
        model.setTrke(trkeIzm);
        jTable2.setModel(model);

        tabelaSorterFilter();
    }

    private void vratiTrke() {
        Zahtev z = new Zahtev();
        z.setOperacija(Operacija.VRATI_TRKE);

        Komunikacija.getInstance().posaljiZahtev(z);
    }

    public void postaviModelRezultata() {
        @SuppressWarnings("unchecked")
        TableModel model = new TabelaDodajRezultateModel();
        jTable1.setModel(model);
    }
    
    public void vratiRezultateTrke(Odgovor o) {
        ArrayList<Rezultat> rez = (ArrayList<Rezultat>) o.getPodaci();
        if (!rez.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Za odabranu trku vec su uneti rezultati, pogledajte ih na formi trke");
            restart();
        }
    }

    public void restart() {
        jTable2.setEnabled(true);
        jTextField1.setEnabled(true);
        jButton1.setEnabled(false);
        jButton3.setEnabled(false);

    }

    private void tabelaSorterFilter() {

        TableRowSorter<TableModel> rowSorter = new TableRowSorter<>(jTable2.getModel());
        jTable2.setRowSorter(rowSorter);

        jTextField1.getDocument().addDocumentListener(new DocumentListener() {

            @Override
            public void insertUpdate(DocumentEvent e) {
                String text = jTextField1.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                String text = jTextField1.getText();

                if (text.trim().length() == 0) {
                    rowSorter.setRowFilter(null);
                } else {
                    rowSorter.setRowFilter(RowFilter.regexFilter("(?i)" + text));
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
            }
        });
    }

    public static Comparator<Rezultat> rezCom = (Rezultat r1, Rezultat r2) -> {
        int r1Com = r1.getKonacnaPozicija();
        int r2Com = r2.getKonacnaPozicija();

        return r1Com - r2Com;
    };

    public void sacuvaniRez(Odgovor o) {
        JOptionPane.showMessageDialog(this, o.getPoruka());
    }
}
